/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LocationRouteImport } from './routes/location'
import { Route as InvestmentRouteImport } from './routes/investment'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as FloorPlansRouteImport } from './routes/floor-plans'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AmenitiesRouteImport } from './routes/amenities'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationRoute = LocationRouteImport.update({
  id: '/location',
  path: '/location',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestmentRoute = InvestmentRouteImport.update({
  id: '/investment',
  path: '/investment',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const FloorPlansRoute = FloorPlansRouteImport.update({
  id: '/floor-plans',
  path: '/floor-plans',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AmenitiesRoute = AmenitiesRouteImport.update({
  id: '/amenities',
  path: '/amenities',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/amenities': typeof AmenitiesRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/floor-plans': typeof FloorPlansRoute
  '/gallery': typeof GalleryRoute
  '/investment': typeof InvestmentRoute
  '/location': typeof LocationRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/amenities': typeof AmenitiesRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/floor-plans': typeof FloorPlansRoute
  '/gallery': typeof GalleryRoute
  '/investment': typeof InvestmentRoute
  '/location': typeof LocationRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/amenities': typeof AmenitiesRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/floor-plans': typeof FloorPlansRoute
  '/gallery': typeof GalleryRoute
  '/investment': typeof InvestmentRoute
  '/location': typeof LocationRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/amenities'
    | '/contact'
    | '/faq'
    | '/floor-plans'
    | '/gallery'
    | '/investment'
    | '/location'
    | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/amenities'
    | '/contact'
    | '/faq'
    | '/floor-plans'
    | '/gallery'
    | '/investment'
    | '/location'
    | '/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/amenities'
    | '/contact'
    | '/faq'
    | '/floor-plans'
    | '/gallery'
    | '/investment'
    | '/location'
    | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AmenitiesRoute: typeof AmenitiesRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  FloorPlansRoute: typeof FloorPlansRoute
  GalleryRoute: typeof GalleryRoute
  InvestmentRoute: typeof InvestmentRoute
  LocationRoute: typeof LocationRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/location': {
      id: '/location'
      path: '/location'
      fullPath: '/location'
      preLoaderRoute: typeof LocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investment': {
      id: '/investment'
      path: '/investment'
      fullPath: '/investment'
      preLoaderRoute: typeof InvestmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/floor-plans': {
      id: '/floor-plans'
      path: '/floor-plans'
      fullPath: '/floor-plans'
      preLoaderRoute: typeof FloorPlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/amenities': {
      id: '/amenities'
      path: '/amenities'
      fullPath: '/amenities'
      preLoaderRoute: typeof AmenitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AmenitiesRoute: AmenitiesRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  FloorPlansRoute: FloorPlansRoute,
  GalleryRoute: GalleryRoute,
  InvestmentRoute: InvestmentRoute,
  LocationRoute: LocationRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
